/*
 * Copyright (c) 2026 LJC
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef BINARY_TREE_H
#define BINARY_TREE_H

/**
 * @brief A database binary tree node
 *
 * A binary tree node in this case is a key-value store.
 * The key is used to manage where each node is in
 * the tree and where to find it, not the data_ptr.
 * Key values should be generated by XXH32 or any
 * other 32-bit hash function. XXH32 is opted for
 * do to its speed over cryptographic security which
 * in this case is not needed.
 */
struct binary_tree_node
{
    unsigned int key;                      /// The key for lookup in the binary tree
    void *data_ptr;                        /// Pointer to the data the node holds
    struct binary_tree_node *left, *right; /// Left and right nodes of the current node
};

struct binary_tree_node *create_binary_tree_node(int key, void *data_ptr);

void binary_tree_insert(struct binary_tree_node **root_ptr, int key, 
    void *data_ptr);

void binary_tree_delete(struct binary_tree_node **root_ptr, int key);

struct binary_tree_node *binary_tree_search(struct binary_tree_node *root, 
    int key);

void free_binary_tree(struct binary_tree_node **root_ptr);

#endif